/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'alertType' : string,
  'farmerId' : bigint,
  'isRead' : boolean,
  'channels' : Array<string>,
  'message' : string,
  'timestamp' : bigint,
  'cropName' : string,
  'mandiName' : string,
}
export interface Mandi {
  'id' : bigint,
  'activeBuyers' : bigint,
  'name' : string,
  'distanceKm' : number,
  'demandLevel' : string,
  'locationZone' : string,
  'specializations' : Array<string>,
}
export interface _SERVICE {
  'addAlert' : ActorMethod<
    [bigint, string, string, string, string, Array<string>],
    bigint
  >,
  'addMandi' : ActorMethod<
    [string, string, number, bigint, Array<string>, string],
    bigint
  >,
  'getAlertsForFarmer' : ActorMethod<[bigint], Array<Alert>>,
  'getMandisByCrop' : ActorMethod<[string], Array<Mandi>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];