/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'farmerId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'channels' : IDL.Vec(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'cropName' : IDL.Text,
  'mandiName' : IDL.Text,
});
export const Mandi = IDL.Record({
  'id' : IDL.Nat,
  'activeBuyers' : IDL.Nat,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'demandLevel' : IDL.Text,
  'locationZone' : IDL.Text,
  'specializations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addMandi' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAlertsForFarmer' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'getMandisByCrop' : IDL.Func([IDL.Text], [IDL.Vec(Mandi)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'farmerId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'channels' : IDL.Vec(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'cropName' : IDL.Text,
    'mandiName' : IDL.Text,
  });
  const Mandi = IDL.Record({
    'id' : IDL.Nat,
    'activeBuyers' : IDL.Nat,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'demandLevel' : IDL.Text,
    'locationZone' : IDL.Text,
    'specializations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addMandi' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAlertsForFarmer' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
    'getMandisByCrop' : IDL.Func([IDL.Text], [IDL.Vec(Mandi)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };